name: Build and Push Docker Image

on:
  push:
    branches: [ main, develop ]

env:
  IMAGE: ${{ secrets.DOCKER_USERNAME }}/my-flask-app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Сборка/пуш для production (main)
    - name: Build & Push (main)
      if: github.ref == 'refs/heads/main'
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: |
          ${{ env.IMAGE }}:latest
          ${{ env.IMAGE }}:${{ github.sha }}

    # Сборка/пуш для development (develop)
    - name: Build & Push (develop)
      if: github.ref == 'refs/heads/develop'
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: |
          ${{ env.IMAGE }}:develop
          ${{ env.IMAGE }}:dev-${{ github.sha }}

    # Условный "деплой"
    - name: Deploy to production
      if: github.ref == 'refs/heads/main'
      run: echo "Deploying to production server..."

    - name: Deploy to development
      if: github.ref == 'refs/heads/develop'
      run: echo "Deploying to development server..."